version: "3"

services:
    client:
        image: edos/client
        ports:
            - "8000:8000"
            - "8010:8010"
        environment:
            - DATABASE=/data/client.sqlite
            - KEY=
            - JWT_SECRET=
        volumes:
            - "/path/to/your/data/folder/:/data/"
        restart: unless-stopped
